name: "RPMTW Translation Scripts"
description: "RPMTW 的 Minecraft 翻譯語系檔案腳本 for Github Action"

branding:
  icon: "arrow-down-circle"
  color: "blue"

inputs:
  action:
    description: "要執行腳本的操作類型"
    required: true
    default: "spider"
  args:
    description: "要執行腳本的參數"
    required: false
    default: ""
  gameVersion:
    description: "遊戲版本"
    required: true
    default: "1.18"

runs:
  using: "composite"
  steps:
    # 安裝 Dart SDK
    - uses: dart-lang/setup-dart@v1
    # 安裝函式庫
    - run: |
        dart pub get --directory=${{ github.action_path }}
      shell: bash
    # 開始執行腳本
    - name: Run scripts ( ${{ inputs.action }} Action )
      run: |
        cd ${{ github.action_path }}
        dart compile exe ./bin/main.dart
        cp ./bin/main ${{ github.workspace }}
        cd ${{ github.workspace }}
        ./main --action ${{ inputs.action }},${{ inputs.args }} --gameVersion ${{ inputs.gameVersion }}
      shell: bash
