name: "RPMTW Translation Scripts"
description: "RPMTW 的 Minecraft 翻譯語系檔案腳本 for Github Action"
author: "The RPMTW Team"
inputs:
  action:
    description: "要執行腳本的操作類型"
    required: true
  args:
    description: "要執行腳本的參數"
    required: false
    default: ""
  gameVersion:
    description: "遊戲版本"
    required: true
    default: "1.18"
  rpmtwToken:
    description: "The token to use for the RPMTW API."
    required: true

runs:
  using: "composite"
  steps:
    - uses: dart-lang/setup-dart@v1
      with:
        # https://dart.dev/get-dart/archive
        version: 2.16.2
    - name: Install dependencies
      run: |
        dart pub get --directory=${{ github.action_path }}
      shell: bash
    - name: Compile the script
      run: dart compile exe bin/rpmtranslator_script.dart -o rpmtranslator_script
      shell: bash
    - name: Run scripts ( ${{ inputs.action }} Action )
      run: ./rpmtranslator_script ${{ inputs.action }} --rpmtwToken ${{ inputs.rpmtwToken }} --gameVersion ${{ inputs.gameVersion }}
      shell: bash
