name: rpmtranslator_script
description: A simple command-line application.
version: 1.0.0

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  archive: ^3.1.5
  args: ^2.3.0
  dio: ^4.0.0
  hive: ^2.1.0
  json5: ^0.7.0
  logger: ^1.1.0
  path: ^1.8.0
  rpmtw_api_client:
    git:
      url: https://github.com/RPMTW/RPMTW-API-Client.git
      ref: feature/curseforge-apis
      path: packages/rpmtw_api_client
  # rpmtw_api_client: ^1.0.8-dev.2
  rpmtw_dart_common_library: ^0.0.4
  toml: ^0.12.0

dev_dependencies:
  build_runner: ^2.1.8
  hive_generator: ^1.1.2
  lints: ^1.0.0
